# Generated by Django 5.2.1 on 2025-09-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('open_ports', models.TextField(blank=True, null=True)),
                ('sql_injection', models.TextField(blank=True, null=True)),
                ('xss', models.TextField(blank=True, null=True)),
                ('findings', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
