# Generated by Django 5.2.1 on 2025-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
