# Generated by Django 5.2.1 on 2025-09-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
