# Generated by Django 5.2.4 on 2025-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanresult_command_used_scanresult_raw_output_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresult',
            old_name='command_used',
            new_name='open_ports',
        ),
        migrations.RenameField(
            model_name='scanresult',
            old_name='raw_output',
            new_name='sql_injection',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='status',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='xss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='findings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
