# Generated by Django 5.2.4 on 2025-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_rename_command_used_scanresult_open_ports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
