# Generated by Django 5.2.1 on 2025-10-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scanresult_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('last_risk_level', models.CharField(max_length=10)),
                ('last_scan_id', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
