# Generated by Django 5.2.1 on 2025-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_scanresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
