# Generated by Django 5.2.1 on 2025-08-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scanresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='status',
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='open_ports',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='sql_injection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='xss',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
