# Generated by Django 5.2.1 on 2025-10-29 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_urlscanhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlscanhistory',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='urlscanhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urlscanhistory',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='urlscanhistory',
            unique_together={('url', 'user')},
        ),
    ]
